version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hunter2

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hunter2
      ME_CONFIG_MONGODB_URL: mongodb://root:hunter2@mongodb:27017/?authMechanism=DEFAULT
    depends_on:
      - "mongodb"
    restart: unless-stopped
    links: 
      - mongodb:mongodb